#####
POST https://localhost:3443/api/auth/accountLogin HTTP/1.1
Content-Type: application/json

{
 "emailHp" : "pengawas@kkpus.id",
 "password": "qwerty123!!"
}
#####
POST https://localhost:3443/api/auth/accountLogin HTTP/1.1
Content-Type: application/json

{
 "emailHp" : "ketua@kkpus.id",
 "password": "qwerty123!!"
}
#####bendahara
POST https://localhost:3443/api/auth/accountLogin HTTP/1.1
Content-Type: application/json

{
 "emailHp" : "bendahara@kkpus.id",
 "password": "qwerty123!!"
}
#####pengawas
PUT https://localhost:3443/api/approvals/pendaftaran/approve/2ea0dcba-d86a-4142-afbf-874960eb5d30 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJfaWQiOiJhMTE2YWYzZS0xMmI5LTExZjEtOWVjZi1mYTE2M2U5YjUyNWIiLCJtZW1iZXJfbm8iOiIwMDEwMTIyNTE2MjMiLCJmdWxsX25hbWUiOiJQZW5nYXdhcyIsImVtYWlsIjoicGVuZ2F3YXNAa2twdXMuaWQiLCJzdGF0dXNfaWQiOjEsImlhdCI6MTc3MjMzMzk1NSwiZXhwIjoxNzcyNDIwMzU1fQ.1yEVBDbLhSAa00U0aVyOEzDX8dn19OQiAW4kNFtkHBo

{
    "action": "approve",
    "notes": "Persetujuan verifikasi pendaftaran."
}
#####ketua
PUT https://localhost:3443/api/approvals/pendaftaran/approve/2ea0dcba-d86a-4142-afbf-874960eb5d30 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJfaWQiOiJhMTE3ZDhjZi0xMmI5LTExZjEtOWVjZi1mYTE2M2U5YjUyNWIiLCJtZW1iZXJfbm8iOiIwMDEwMTIyNTE2MjUiLCJmdWxsX25hbWUiOiJLZXR1YSIsImVtYWlsIjoia2V0dWFAa2twdXMuaWQiLCJzdGF0dXNfaWQiOjEsImlhdCI6MTc3MjMzMzk5MywiZXhwIjoxNzcyNDIwMzkzfQ.VFKic666XW5ALZUJQrbrrI1JZL_QUTaIN67yenrqyLQ

{
    "action": "approve",
    "notes": "Persetujuan verifikasi pendaftaran."
}
#####pengawas penarikan
PUT https://localhost:3443/api/approvals/penarikan/approve/49 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJfaWQiOiJhMTE2YWYzZS0xMmI5LTExZjEtOWVjZi1mYTE2M2U5YjUyNWIiLCJtZW1iZXJfbm8iOiIwMDEwMTIyNTE2MjMiLCJmdWxsX25hbWUiOiJQZW5nYXdhcyIsImVtYWlsIjoicGVuZ2F3YXNAa2twdXMuaWQiLCJzdGF0dXNfaWQiOjEsImlhdCI6MTc3MjMzMzk1NSwiZXhwIjoxNzcyNDIwMzU1fQ.1yEVBDbLhSAa00U0aVyOEzDX8dn19OQiAW4kNFtkHBo

{
    "action": "approve",
    "notes": "Persetujuan pembiayaan oleh pengawas."
}
#####ketua penarikan
PUT https://localhost:3443/api/approvals/penarikan/approve/49 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJfaWQiOiJhMTE3ZDhjZi0xMmI5LTExZjEtOWVjZi1mYTE2M2U5YjUyNWIiLCJtZW1iZXJfbm8iOiIwMDEwMTIyNTE2MjUiLCJmdWxsX25hbWUiOiJLZXR1YSIsImVtYWlsIjoia2V0dWFAa2twdXMuaWQiLCJzdGF0dXNfaWQiOjEsImlhdCI6MTc3MjMzMzk5MywiZXhwIjoxNzcyNDIwMzkzfQ.VFKic666XW5ALZUJQrbrrI1JZL_QUTaIN67yenrqyLQ

{
    "action": "approve",
    "notes": "Persetujuan pembiayaan oleh ketua."
}
#####bendahara penarikan
PUT https://localhost:3443/api/approvals/penarikan/approve/49 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJfaWQiOiJhMTE3ZDczMy0xMmI5LTExZjEtOWVjZi1mYTE2M2U5YjUyNWIiLCJtZW1iZXJfbm8iOiIwMDEwMTIyNTE2MjQiLCJmdWxsX25hbWUiOiJCZW5kYWhhcmEiLCJlbWFpbCI6ImJlbmRhaGFyYUBra3B1cy5pZCIsInN0YXR1c19pZCI6MSwiaWF0IjoxNzcyMzM2MDI2LCJleHAiOjE3NzI0MjI0MjZ9.4EjiHh2Joem_v4oEUhQy2ZSSTcm7FC0g2tDYirb0cVg

{
    "action": "approve",
    "notes": "Persetujuan pembiayaan oleh bendahara."
}
#####cash disbursement (bendahara)
POST https://localhost:3443/api/simpanan/penarikan/cash-disburse/49 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJfaWQiOiJhMTE3ZDczMy0xMmI5LTExZjEtOWVjZi1mYTE2M2U5YjUyNWIiLCJtZW1iZXJfbm8iOiIwMDEwMTIyNTE2MjQiLCJmdWxsX25hbWUiOiJCZW5kYWhhcmEiLCJlbWFpbCI6ImJlbmRhaGFyYUBra3B1cy5pZCIsInN0YXR1c19pZCI6MSwiaWF0IjoxNzcyMzM2MDI2LCJleHAiOjE3NzI0MjI0MjZ9.4EjiHh2Joem_v4oEUhQy2ZSSTcm7FC0g2tDYirb0cVg

{}
#####pengawas pembiayaan
PUT https://localhost:3443/api/approvals/pembiayaan/approve/{financing_id} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {pengawas_token}

{
    "action": "approve",
    "notes": "Persetujuan pembiayaan oleh pengawas."
}
#####ketua pembiayaan
PUT https://localhost:3443/api/approvals/pembiayaan/approve/{financing_id} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {ketua_token}

{
    "action": "approve",
    "notes": "Persetujuan pembiayaan oleh ketua."
}
#####bendahara pembiayaan
PUT https://localhost:3443/api/approvals/pembiayaan/approve/{financing_id} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {bendahara_token}

{
    "action": "approve",
    "notes": "Persetujuan pembiayaan oleh bendahara."
}
