name: Deploy to VPS

on:
  push:
    branches:
      - main   # ganti sesuai branch utama project

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build React (ignore ESLint warnings)
        run: npm run build
        env:
          CI: false   # ✅ penting, biar warning tidak dianggap error

      - name: Deploy to VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "build/*"
          target: "/var/www/react-dashboard/" # sesuaikan dengan project ini
name: Deploy to VPS

on:
  push:
    branches:
      - main   # ganti sesuai branch utama project

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build React (ignore ESLint warnings)
        run: npm run build

      - name: Deploy to VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "build/*"
          target: "/var/www/kkpus.id/" # sesuaikan dengan project ini
