name: Deploy to VPS

on:
  push:
    branches:
      - main # ganti kalau branch utamamu berbeda

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies & build
        run: |
          npm run build

      - name: Deploy to VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "build/*"
          target: "/var/www/kkpus.id/" # <- untuk repo dashboard
